language: node_js
node_js:
  - "0.10.36"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH=$HOME/.meteor:$PATH
  - npm install -g spacejam protractor

install:
  - cd tests && npm install

before_script: $TRAVIS_BUILD_DIR/bin/travis-meteor-login.sh

script: $TRAVIS_BUILD_DIR/bin/travis-test.sh

after_success: $TRAVIS_BUILD_DIR/bin/travis-meteor-deploy.sh
